# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           :categories/:title/
relative_permalinks: false

# Setup
title:               Harold Kyle
url:                 http://haroldkyle.com
baseurl:             /
paginate:            5
assets:				       "/assets/"
description:         "Hiking, coding, and cast iron."
archive_base:        "category"

# About/contact
author:
  name:              Harold Kyle
  url:               http://haroldkyle.com
  email:             harold@boxcarpress.com

# Custom vars
version:             1.0.0

redcarpet:
  extensions:        ["smart"]

# Resizing images
mini_magick:
    thumbnail:
        source:       /assets/images/full
        destination:  /assets/images/thumbnail
        resize:       "100x100"
    medium:
        source:       /assets/images/full
        destination:  /assets/images/medium
        resize:       "720x540"
